# TODO: we should to add a normal configuration for unit testing
spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:~/clinic-manager-db
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties.hibernate.dialect: org.hibernate.dialect.H2Dialect